### ISSUE TITLE
Implementar subida fotos en: CATEGORÍA y PRODUCTO

### ISSUE THREAD

**Issue by huasipango** [huasipango/RestaurantATM#3]
![imagen](https://user-images.githubusercontent.com/20136451/42798583-f1a06400-8959-11e8-9a81-a1457061d0c9.png)
https://code.tutsplus.com/es/tutorials/how-to-program-with-yii2-uploading-files--cms-23511

**Comment by 8-30** [comment]
ya termine

**Comment by huasipango** [comment]
Hecho exitosamente
